# Determinan Matrix

Sifat-sifat matrix Determinan

Sifat 1:
jika didalam suatu matrik memiliki 2 baris dengan nilai yang sama maka hasilnya 0

sifat 2:
ika matrik b 2* matrik a itu bisa dihitung dengan rumus 2^3(ordo)* det i = det g

sifat 3:
ika matrik b colom pertama 2* matrik a colom pertama itu akan menghasilkan 2*det a

In [10]:
import numpy as np

a = np.array([[1,0],[0,1]])
b = np.array([[1,0,0],[0,1,0],[0,0,1]])
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
h = np.array([[6,8],[4,2]])
i = np.array([[6,8],[2,1]])
j = np.array([[6,4],[4,1]])
k = np.array([[2*3,2*4],[2,1]])
l = np.array([[2*3,4],[2*2,1]])
m = np.array([[4,1],[2,1]])
n = np.array([[7,5],[2,1]])
o = np.array([[2,3,2],[0,2,2],[0,0,2]])

print(f'{a}\nDeterminan Matrix a = {np.linalg.det(a)}\n')
print(f'{b}\nDeterminan Matrix b = {np.linalg.det(b)}\n')
print(f'{c}\nDeterminan Matrix c = {np.linalg.det(c)}\n')
print(f'{d}\nDeterminan Matrix d = {np.linalg.det(d)}\n')
print(f'{e}\nDeterminan Matrix e = {np.linalg.det(e)}\n')
print(f'{f}\nDeterminan Matrix f = {np.linalg.det(f)}\n')
print(f'{g}\nDeterminan Matrix g = {np.linalg.det(g)}\n')
print(f'{h}\nDeterminan Matrix h = {np.linalg.det(h)}\n')
print(f'{i}\nDeterminan Matrix i = {np.linalg.det(i)}\n')
print(f'{j}\nDeterminan Matrix j = {np.linalg.det(j)}\n')
print(f'{j}\nDeterminan Matrix k = {np.linalg.det(k)}\n')
print(f'{j}\nDeterminan Matrix l = {np.linalg.det(l)}\n')
print(f'{j}\nDeterminan Matrix m = {np.linalg.det(m)}\n')
print(f'{j}\nDeterminan Matrix n = {np.linalg.det(n)}\n')
print(f'{j}\nDeterminan Matrix o = {np.linalg.det(o)}\n')

# ada matrix kemudian akan dicari determinan nya, misal ordo 2x2 pada matrix h jadi 6x2=12 8x4= 32 jadi 12-34=19.9 dibublatkan jadi 20
# Determinan matriks h dapat diperoleh dengan mengurangkan hasil kali elemen-elemen diagonal utama dengan hasil kali elemen-elemen diagonal kedua.


[[1 0]
 [0 1]]
Determinan Matrix a = 1.0

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinan Matrix b = 1.0

[[1 2 1]
 [3 1 2]
 [2 1 2]]
Determinan Matrix c = -3.000000000000001

[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinan Matrix d = 3.000000000000001

[[1 2 1]
 [2 4 2]
 [2 1 2]]
Determinan Matrix e = 0.0

[[1 2 1]
 [2 4 2]
 [2 4 3]]
Determinan Matrix f = 0.0

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinan Matrix g = 24.000000000000014

[[6 8]
 [4 2]]
Determinan Matrix h = -19.999999999999996

[[6 8]
 [2 1]]
Determinan Matrix i = -9.999999999999998

[[6 4]
 [4 1]]
Determinan Matrix j = -9.999999999999998

[[6 4]
 [4 1]]
Determinan Matrix k = -9.999999999999998

[[6 4]
 [4 1]]
Determinan Matrix l = -9.999999999999998

[[6 4]
 [4 1]]
Determinan Matrix m = 2.0

[[6 4]
 [4 1]]
Determinan Matrix n = -2.9999999999999982

[[6 4]
 [4 1]]
Determinan Matrix o = 7.999999999999998

